---
ID: "c3ea1b73-8d91-4c8d-b32e-63dffc9d44bd"
Parent: "58c7b74f-d255-4002-9b02-ce1b0d25624a"
Template: "58c7b74f-d255-4002-9b02-ce1b0d25624a"
Path: /sitecore/templates/Project/FastLane/Page Templates/ContentPagewithSidebar/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "/sitecore/media library/Project/FastLaneTenant/FastLaneWebsite/PageIcons/-/media/3DB7402B3BF84C49800F7FD346A73081.ashx"
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{C14B6289-8AC2-439C-9E5B-40DE9F820C3F}"
- ID: "4a749557-242b-4372-8a20-b2db9d406301"
  Hint: __AutoThumbnails
  Value: 
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{CF913994-CC05-4D20-B38A-9CF1E73F5951}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "52712555-1621-43d9-88bf-bc4a3b2d7fc1"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250616T144715Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7da53751-d988-4f7c-b2ca-4d9fc0d87b90"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250725T080541Z
