---
ID: "93e5f115-e8b8-4eed-89d5-b73e89af958b"
Parent: "e58b7dbf-2a15-4a94-ad45-9c250ac1ac68"
Template: "e58b7dbf-2a15-4a94-ad45-9c250ac1ac68"
Path: /sitecore/templates/Feature/FastLane/Renderings/ContentCard/ContentCard/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "/sitecore/media library/Project/FastLaneTenant/shared/ComponentIcons/-/media/6CC403E3F012445EA8507ADF537153B1.ashx?thn=1&db=master"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "c7223796-5947-48a3-842d-4f03137d86ce"
Languages:
- Language: en
  Fields:
  - ID: "30e85e5d-e00a-4864-b358-7624d511deb4"
    Hint: __Unversioned revision
    Value: "d8d9a23f-d069-4542-8e92-4fa571d8fa66"
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: 
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250604T101427Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b3d327e1-2a34-4ab5-8e5b-3e6f8cdbaae3"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\andy.cohen@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250630T164216Z
