---
ID: "640c1d48-b135-43d2-beb2-ac8e839dadea"
Parent: "bfe61dab-2bb3-4884-91e8-0ffcfefde91e"
Template: "bfe61dab-2bb3-4884-91e8-0ffcfefde91e"
Path: /sitecore/templates/Feature/FastLane/Renderings/BlogPostList/BlogPostList/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{67E51ACA-745B-4251-A749-CAE42832D061}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "4227ff6f-f7fd-4c5b-be9b-764b2b1c5af1"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251111T054009Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7fb0cfce-a7a5-4e13-be4f-6b75555a0a15"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251111T054049Z
