---
ID: "f5a1c752-44c4-4edc-98b4-ca1ce40b111e"
Parent: "626922a1-ae45-426c-a1ea-79181182970b"
Template: "626922a1-ae45-426c-a1ea-79181182970b"
Path: /sitecore/templates/Feature/FastLane/Renderings/Location/Location Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {7B43AF31-7892-4886-B7A4-6CF5E52E6B04}
    {626922A1-AE45-426C-A1EA-79181182970B}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "5332f4ac-0b3d-4555-99f3-646510926514"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "80b1f309-1487-45a5-bb34-8cb88a3af91e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250915T081333Z
