---
ID: "f73728be-a898-4721-aea5-de7397eaaa70"
Parent: "e19d8936-8b8b-4d06-a07d-e8856002dd70"
Template: "e19d8936-8b8b-4d06-a07d-e8856002dd70"
Path: /sitecore/templates/Feature/FastLane/Renderings/FLLinkList/FL Link List Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {51FFA782-5DE3-47BD-846F-3560A264E83D}
    {E19D8936-8B8B-4D06-A07D-E8856002DD70}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "02c4c3be-01e7-44f4-a038-b1d9f172c057"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T061559Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d48d3f58-31ab-4ab9-9c17-e1c18a07c1da"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250811T134828Z
