---
ID: "c6f3ceaf-e764-4d88-a03f-69d5a37ed652"
Parent: "ed7c9776-4c16-4c64-9eec-642590e78b71"
Template: "ed7c9776-4c16-4c64-9eec-642590e78b71"
Path: /sitecore/templates/Project/FastLane/Page Designs/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {3DB0830B-A06A-41E3-B476-AD10270CAB21}
    {1105B8F8-1E00-426B-BF1F-C840742D827B}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250124T121459Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0de3ff6f-99a4-4aa5-9260-e9c72a8982ea"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250124T121500Z
