---
ID: "c51fb933-23b7-4fd4-8c8b-ee1aca17ed73"
Parent: "c9043bc8-3eeb-435e-9e46-cde436879a6c"
Template: "c9043bc8-3eeb-435e-9e46-cde436879a6c"
Path: /sitecore/templates/Feature/FastLane/Renderings/Modal/Modal/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "/sitecore/media library/Project/FastLaneTenant/shared/ComponentIcons/-/media/062BAE2F47274538944AF4738F64090F.ashx?thn=1&db=master"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "cf2c5508-6854-4b88-a541-3b36b809a527"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250305T174102Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3a7ade33-0854-4800-b149-0b5f2db5122f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\andy.cohen@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250629T181239Z
