---
ID: "9329f857-7a00-494d-ad31-65d496b0c1be"
Parent: "3d2a5da1-4d9c-4c21-89e8-693c36534fe9"
Template: "3d2a5da1-4d9c-4c21-89e8-693c36534fe9"
Path: /sitecore/templates/Feature/FastLane/Renderings/MegaNav/MegaNav Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {9E43E6EC-A85D-4206-914A-5FCA2349BD50}
    {3D2A5DA1-4D9C-4C21-89E8-693C36534FE9}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "b776f1fa-7590-4800-a2e7-9c93100d66e6"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "20136f3d-58c0-445b-9bdd-866dae68f7f4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250429T121208Z
