---
ID: "fc2c75de-e77d-4b39-a01e-b21a9babc39c"
Parent: "9878abdd-0000-4881-a7fc-366da38f4bd1"
Template: "9878abdd-0000-4881-a7fc-366da38f4bd1"
Path: /sitecore/templates/Project/FastLane/General Components/CardLinkType/CardLinkType/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250623T072126Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f3aab21f-9465-46d3-97a4-352b2379cc33"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250623T072132Z
    - ID: "eba40eb0-8201-4ef4-98bd-717d6f30a4e2"
      Hint: LinkType
      Value: $name
