---
ID: "ad5b5ff3-72d1-408b-ae4b-bbe228c4db25"
Parent: "7745ad5c-5c25-472f-8cb4-5470ec8d15c0"
Template: "7745ad5c-5c25-472f-8cb4-5470ec8d15c0"
Path: /sitecore/templates/Feature/FastLane/Renderings/SpotlightCarousel/SpotlightCarousel Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {DDF77939-0860-4D1D-B80B-AB99B18E56F7}
    {7745AD5C-5C25-472F-8CB4-5470EC8D15C0}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "19aeda61-eb60-4c55-9e93-a151ccb0147b"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8c0e5a47-440b-4dff-b48b-fd6788ff6b1c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251208T145353Z
