---
ID: "2d497398-7537-4093-8e9c-a66d63485212"
Parent: "e841e10b-6f41-46ad-ada8-3a1f274a7402"
Template: "e841e10b-6f41-46ad-ada8-3a1f274a7402"
Path: /sitecore/templates/Feature/FastLane/Renderings/VideoPlayer/Rendering Parameters/VideoPlayer/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5a865138-ced8-4145-b088-7c34efcdaef4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250320T072356Z
