---
ID: "6896910b-ea78-44c4-a9d9-9ff35e01eee5"
Parent: "708ef6c7-8bd0-48d3-ac4d-ae4e97daf08e"
Template: "708ef6c7-8bd0-48d3-ac4d-ae4e97daf08e"
Path: /sitecore/templates/Feature/FastLane/Renderings/NotificationBanner/NotificationBanner Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {06668086-6F8C-48CE-AE14-D10EB7C93136}
    {708EF6C7-8BD0-48D3-AC4D-AE4E97DAF08E}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "6ca0314f-9fb5-4006-bec4-f9ea63fa45f2"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250221T100122Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "137244e8-464b-4397-ad9e-9137c246872b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\andy.cohen@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250628T164326Z
