---
ID: "2494c331-cd2b-4882-a592-11a4ad4daa72"
Parent: "1fc7a7a6-2002-4170-a008-56ccafeb2725"
Template: "1fc7a7a6-2002-4170-a008-56ccafeb2725"
Path: /sitecore/templates/Project/FastLane/Partial Designs/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {0719ACC8-E882-4F78-AA0B-36B258C3DE9B}
    {FD2059FD-6043-4DFE-8C04-E2437CE87634}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250124T121459Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ea473714-e31f-4e17-abc4-bfbe78bf7e44"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250124T121500Z
