---
ID: "497852fe-b8ba-44f6-a57c-fb47fb16715c"
Parent: "858154aa-da7b-4a6a-a94c-f9fac2dc0672"
Template: "858154aa-da7b-4a6a-a94c-f9fac2dc0672"
Path: /sitecore/templates/Feature/FastLane/Renderings/SpotlightCarousel/SpotlightCarouselSlide Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {B9F1D392-12D8-4198-8C53-F5803CC361C5}
    {858154AA-DA7B-4A6A-A94C-F9FAC2DC0672}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "8f2a0cdc-621b-48da-9044-29093e587f7a"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "01cf0e89-100b-4cef-a84f-528b647f8014"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251209T102917Z
