---
ID: "76e9f103-954a-4aa5-8f5d-7a12056a7465"
Parent: "22dc6cb6-d9df-4c4c-b1d7-05baf14e699f"
Template: "22dc6cb6-d9df-4c4c-b1d7-05baf14e699f"
Path: /sitecore/templates/Feature/FastLane/Renderings/Accordion/AccordionPanel/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "/sitecore/media library/Project/FastLaneTenant/shared/ComponentIcons/-/media/A7492BF076F847AE900339F299F713B3.ashx?thn=1&db=master"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "622d0a2e-f8b4-44d9-8a1d-3b8503b63382"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250629T181417Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\andy.cohen@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\andy.cohen@altudo.co
    - ID: "7006ed49-6073-421c-a7a7-ac8d2b2bec94"
      Hint: AccordionPanelTitle
      Value: $name
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "46ac565c-df1b-4afa-9be5-ad46bceb127f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250818T091228Z
