---
ID: "c4cc70d6-6db8-4374-a79c-f088f646ff50"
Parent: "95ac8dba-1021-4c14-99e8-6d3d9cbb42be"
Template: "95ac8dba-1021-4c14-99e8-6d3d9cbb42be"
Path: /sitecore/templates/Feature/FastLane/Renderings/MegaNav/Rendering Parameters/MegaNav/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "106db1fd-60a6-4962-91bb-d037160749f0"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250429T122243Z
