---
ID: "ab233411-c6ac-46a8-8e4d-5b63a1db34c8"
Parent: "9b0ee820-703c-4649-9eef-684a1b297ffd"
Template: "9b0ee820-703c-4649-9eef-684a1b297ffd"
Path: /sitecore/templates/Feature/FastLane/Renderings/SocialLinks/SocialLinks/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "/sitecore/media library/Project/FastLaneTenant/shared/ComponentIcons/-/media/B02A98B3219742C3A59FC7C8EC8D1EE4.ashx?thn=1&db=master"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "e8b6ff76-8c5e-45ce-8152-9d3cfb8f5873"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250224T120953Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d367dbcd-0121-4dbc-bd30-68972292f7a8"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\andy.cohen@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250629T181325Z
