---
ID: "31f27958-4b62-4895-a09a-eeb54f61d1ca"
Parent: "d84acb00-12da-4250-aa75-d9f06cfaba21"
Template: "d84acb00-12da-4250-aa75-d9f06cfaba21"
Path: /sitecore/templates/Feature/FastLane/Renderings/Carousel/Rendering Parameters/Carousel/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f1729a82-63f6-47d1-b0e4-9e3bfeeb4d69"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250320T072505Z
