---
ID: "deb7abf9-6ad1-42ab-aa71-a3023dc6aa98"
Parent: "c449bde0-4ca5-49e7-bd94-33abd9e0ff99"
Template: "c449bde0-4ca5-49e7-bd94-33abd9e0ff99"
Path: /sitecore/templates/Feature/FastLane/Renderings/NotificationBanner/Rendering Parameters/NotificationBanner/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ca79eede-9580-4391-a36a-c06a5d23accb"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250320T072436Z
