---
ID: "9bafccb3-2a59-4d06-b92d-60ced9023b9f"
Parent: "91e9502e-e2c8-41cc-aef9-583d295a43ba"
Template: "91e9502e-e2c8-41cc-aef9-583d295a43ba"
Path: /sitecore/templates/Feature/FastLane/Renderings/SpotlightCarousel/Rendering Parameters/SpotlightCarouselSlide Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6f0aacbd-7e04-4342-94be-c82c6c6a94c6"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251209T102906Z
