---
ID: "3e884687-0182-4da5-84a6-7d804fccd79a"
Parent: "2fe2f896-d9a5-46de-a738-c779b0632223"
Template: "2fe2f896-d9a5-46de-a738-c779b0632223"
Path: /sitecore/templates/Project/FastLane/General Components/LinkLevels/LinkLevel/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250228T194705Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a33e6e93-7bc7-4adf-8157-a70a3ff34000"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250228T194705Z
