---
ID: "7dd8d843-738a-4c5c-9873-a60eda13dde0"
Parent: "475273fb-fbc5-4063-a429-f30df04d9802"
Template: "475273fb-fbc5-4063-a429-f30df04d9802"
Path: /sitecore/templates/Project/FastLane/Page/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {475273FB-FBC5-4063-A429-F30DF04D9802}
    {C14B6289-8AC2-439C-9E5B-40DE9F820C3F}
- ID: "4a749557-242b-4372-8a20-b2db9d406301"
  Hint: __AutoThumbnails
  Value: 
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{CF913994-CC05-4D20-B38A-9CF1E73F5951}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "385791ee-e4db-4f85-9f48-97dbf0b4c468"
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250124T121459Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "7cba72f9-1513-41af-ba26-de761f138805"
      Hint: Title
      Value: $name
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "830cbb83-00c0-4b77-92e7-8a2a20b2fdbc"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251104T095945Z
