---
ID: "b0f5bdaa-0930-4dec-8190-6b13abea73dc"
Parent: "b0c2f493-d077-482f-a054-bf3a9cc91b8a"
Template: "b0c2f493-d077-482f-a054-bf3a9cc91b8a"
Path: /sitecore/templates/Feature/FastLane/Renderings/SpotlightCarousel/Rendering Parameters/SpotlightCarousel Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c17c541c-a989-44e1-b8e7-c2c4a9a783e5"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251208T145347Z
