---
ID: "dc2c36fc-b880-4156-a82a-a7ba3690b7d0"
Parent: "f760f9c9-43d5-4863-9168-1968102f0609"
Template: "f760f9c9-43d5-4863-9168-1968102f0609"
Path: /sitecore/templates/Feature/FastLane/Renderings/BlogPostList/BlogPostList Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {BFE61DAB-2BB3-4884-91E8-0FFCFEFDE91E}
    {F760F9C9-43D5-4863-9168-1968102F0609}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "7a49c358-b0d5-42c8-9d76-61e1dd66bd44"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "24c781fa-1ea1-4067-8b08-4b64986fdb30"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251111T053123Z
