---
ID: "8f44c8c2-6203-4c7f-869d-7f3b48ee7151"
Parent: "adbf2ebd-e4dd-47e0-b564-ba2f9c4a18aa"
Template: "adbf2ebd-e4dd-47e0-b564-ba2f9c4a18aa"
Path: /sitecore/templates/Project/FastLane/General Components/ButtonVariants/ButtonVariant/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250224T085319Z
    - ID: "33ebeb3b-ab30-453e-b594-ce36c1c8fe0c"
      Hint: Name
      Value: $name
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "13b3bd5a-6f3e-42e2-9e77-6f562be40f1f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250224T085323Z
