---
ID: "a1becff7-5282-498c-89b3-cdf3f336c296"
Parent: "2df3ccf2-a8fd-4859-8927-1cec6cf3ec6c"
Template: "2df3ccf2-a8fd-4859-8927-1cec6cf3ec6c"
Path: /sitecore/templates/Feature/FastLane/Renderings/Tabs/Rendering Parameters/Tab/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7e846ae2-c3cb-4e2e-89af-f0be3c65ecaf"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\andy.cohen@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250418T130824Z
