---
ID: "7ffbf3f6-481b-4d02-b56e-5ebdc4e70a40"
Parent: "f4a48a63-3f94-4a1a-9568-64ff0088e59d"
Template: "f4a48a63-3f94-4a1a-9568-64ff0088e59d"
Path: /sitecore/templates/Feature/FastLane/Renderings/ContentCard/Rendering Paramters/ContentCard/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250220T110911Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "7f9e2455-9589-4e65-86c3-70c454e66341"
      Hint: LinkType
      Value: Button
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f5fc367b-f51f-493b-8cd3-34585694cdd5"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\andy.cohen@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250630T105002Z
    - ID: "dbd05ec5-e687-488a-9372-9af706a1777b"
      Hint: HeaderTag
      Value: 
    - ID: "f2dc5aaa-a0c3-4507-b292-83b69931b439"
      Hint: ImageOrder
      Value: 
