---
ID: "059987d9-3b20-4e51-bf54-d7eab021829d"
Parent: "ff6f3c81-a2b9-400a-8bfb-1d324b208971"
Template: "ff6f3c81-a2b9-400a-8bfb-1d324b208971"
Path: /sitecore/templates/Project/FastLane/General Components/HeaderTags/HeaderTags/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250203T140129Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "84841c1f-5a17-4c6e-b704-008f868ca71c"
      Hint: Header
      Value: $name
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e657542a-92c8-480e-af75-6e1411455a29"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250203T140207Z
