---
ID: "91457ba9-e7d6-4283-a9f3-d3c33371db27"
Parent: "d95e1a5f-301a-48af-9fa1-cf15f41e81e0"
Template: "d95e1a5f-301a-48af-9fa1-cf15f41e81e0"
Path: /sitecore/templates/Feature/FastLane/Renderings/Carousel/Carousel Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {3C7402CF-2DF9-49C7-8ACF-6DD0F35E8864}
    {D95E1A5F-301A-48AF-9FA1-CF15F41E81E0}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "4105a81c-1210-4041-ab57-548c47c5f468"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250218T120446Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9bfdcb68-2661-47a0-ac9b-3b78f7064940"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\andy.cohen@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250628T164209Z
