---
ID: "a5c10b08-ea18-4c38-b0e6-44fb254d21c0"
Parent: "51ffa782-5de3-47bd-846f-3560a264e83d"
Template: "51ffa782-5de3-47bd-846f-3560a264e83d"
Path: /sitecore/templates/Feature/FastLane/Renderings/FLLinkList/FL Link List/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{6F108E3C-5D57-42F8-A910-C22920269B0A}"
- ID: "f7b94d8c-a842-49f8-ab7a-2169d00426b0"
  Hint: __Should Not Organize In Bucket
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20111206T092520Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a943f596-181c-4434-85d3-3ca4c33421aa"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250811T124448Z
