---
ID: "1df06bb8-25fd-4eab-81d7-afda7e19c17d"
Parent: "a0e5eeb2-50ad-4241-800d-08a690247b28"
Template: "a0e5eeb2-50ad-4241-800d-08a690247b28"
Path: /sitecore/templates/Feature/FastLane/Renderings/LanguageSelector/LanguageSelector/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251031T121132Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7f6475fa-7599-4eec-98e1-a3fbdbfbf2e7"
    - ID: "9f7e8673-9e92-4e32-a4b1-b9a1def86333"
      Hint: LanguageLabel
      Value: Language
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251031T121142Z
