---
ID: "12bf1010-8698-4917-811b-8c298ca31c54"
Parent: "23b9e274-19b8-45f9-83c1-0c09843980e8"
Template: "23b9e274-19b8-45f9-83c1-0c09843980e8"
Path: /sitecore/templates/Feature/FastLane/Renderings/ContentCard/ContentCard Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {E58B7DBF-2A15-4A94-AD45-9C250AC1AC68}
    {23B9E274-19B8-45F9-83C1-0C09843980E8}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "6b9905bb-0556-42ff-883c-d3b42396b8d5"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250324T154350Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b099ae1f-4a12-4b45-8136-2db1d36c0aa9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\andy.cohen@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250628T164120Z
