---
ID: "18f0575a-0ec6-4380-a5c1-702b7edd89c9"
Parent: "40588f73-b6d1-4345-8aff-638137ffdbfc"
Template: "40588f73-b6d1-4345-8aff-638137ffdbfc"
Path: /sitecore/templates/Feature/FastLane/Renderings/Tabs/Tab/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "/sitecore/media library/Project/FastLaneTenant/shared/ComponentIcons/-/media/A7492BF076F847AE900339F299F713B3.ashx?thn=1&db=master"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "622d0a2e-f8b4-44d9-8a1d-3b8503b63382"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250629T181417Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\andy.cohen@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\andy.cohen@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d07f6ca3-4827-496e-98a8-d6ffc1563a82"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\andy.cohen@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250629T181426Z
