---
ID: "b804cbcd-69ac-4746-b911-80046ef6dd36"
Parent: "93a9e22d-c09b-4a45-91be-4c2b3aa02d54"
Template: "93a9e22d-c09b-4a45-91be-4c2b3aa02d54"
Path: /sitecore/templates/Feature/FastLane/Renderings/Accordion/Accordion/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "/sitecore/media library/Project/FastLaneTenant/shared/ComponentIcons/-/media/450941F16F244DB8913D9667E452678F.ashx?thn=1&db=master"
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{22DC6CB6-D9DF-4C4C-B1D7-05BAF14E699F}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "433759b6-c30b-4481-a50e-0b1995c16525"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250417T183304Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\andy.cohen@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\andy.cohen@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "43281cb0-ee41-419c-a61e-e64b6df9d1b3"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250820T121708Z
