---
ID: "f4bef336-a81a-4029-8094-d7c34178e266"
Parent: "6c8b7049-2316-4b7b-b1be-2ef9746a1531"
Template: "6c8b7049-2316-4b7b-b1be-2ef9746a1531"
Path: /sitecore/templates/Feature/FastLane/Renderings/FLRichText/Rendering Parameters/FLRichText/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d965a6fa-dcb7-459f-abba-106234759f8b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250828T065944Z
