---
ID: "b4a3f217-20fc-4c2f-a242-a829341bb58c"
Parent: "21f3c2d7-cda1-4db8-8a38-707cc3f2bbab"
Template: "21f3c2d7-cda1-4db8-8a38-707cc3f2bbab"
Path: /sitecore/templates/Project/FastLane/Folder Templates/BlogArticle/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251215T154810Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c80a09db-758d-4ebe-9502-3a2489dafc4c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251215T154810Z
