---
ID: "eeee957f-2ba2-4a9e-9e23-d80310a1af13"
Parent: "3f1e3a73-356c-4110-ba9c-6caaaeaa6d5a"
Template: "3f1e3a73-356c-4110-ba9c-6caaaeaa6d5a"
Path: /sitecore/templates/Feature/FastLane/Renderings/Modal/Modal Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {C9043BC8-3EEB-435E-9E46-CDE436879A6C}
    {3F1E3A73-356C-4110-BA9C-6CAAAEAA6D5A}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "82aca95f-9851-43e8-9fb9-f2d41ccccb93"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250305T174111Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6f45f9b6-dac1-4949-9af3-869c5e17ec21"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\andy.cohen@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250628T164304Z
