---
ID: "7cf82252-24eb-4748-ac2f-7e8c2590037b"
Parent: "efbf9e77-b836-4d15-8ac5-72cc758d375b"
Template: "efbf9e77-b836-4d15-8ac5-72cc758d375b"
Path: /sitecore/templates/Feature/FastLane/Renderings/VideoPlayer/VideoPlayer Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {D7D0E2DB-4BE9-4942-9A0F-5499298C0806}
    {EFBF9E77-B836-4D15-8AC5-72CC758D375B}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "597c0f45-125b-4071-acef-cb42711a4aad"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250307T132143Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "518781f3-51f4-40d3-8167-7bc0d7d6c197"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\andy.cohen@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250628T164442Z
