---
ID: "ac7bdfc3-c60c-49a8-8f64-10ee8f11c701"
Parent: "e8a234fd-fe5c-4359-8037-6857132fecdc"
Template: "e8a234fd-fe5c-4359-8037-6857132fecdc"
Path: /sitecore/templates/Feature/FastLane/Renderings/LanguageSelector/Rendering Parameters/LanguageSelector Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6a3e88fc-337f-4d2d-af31-8959a6cfc11c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\karthikeyan.kumaravel@altudo.co
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251031T111959Z
